FROM golang:1.16-alpine

WORKDIR /go/src/app

ENV GO111MODULE=on

RUN go mod init github.com/IlConteCvma/SDCC_Project

RUN go mod tidy

COPY peer/*.go ./peer/
COPY utility/*.go ./utility/
COPY menu/*.go ./menu/


RUN go install ./peer

CMD [ "sh", "-c", "${GOPATH}/bin/peer" ]